eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9102
spring:
  application:
    name: user-service2
  zipkin:
    base-url: http://localhost:9002
  sleuth:
    sampler:
      percentage: 1.0
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization:
      indent_output: true
endpoints:
  health:
sensitive: false
