server:
  port: 9103
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
spring:
  boot:
    admin:
      url: http://localhost:9021  
management:
  security:
    enabled: true
